# this is simply copied over from config/config_designers.yml

# project definitions
project: mydoc_designers
audience: designers
product: doc
platform: all
version: all
output: web
destination: ../doc_outputs/mydoc/designers
topnav_title: vulkan基础教程
homepage_title: vulkan基础教程
site_title: vulkan基础教程
project_folder: mydoc
company_name: AICDG
footer_image_location: 
github_editme_path: 
disqus_shortname: vulkan-basic
# variables


sidebar_tagline: 目录
sidebar_version: Version 0.01
theme_file: theme-green.css
pdf_file_name: mydoc_designers_pdf.pdf

# the algolia entries here are experimental only.

#gems:
#  - algoliasearch-jekyll
#algolia:
#  application_id: 'HXUBJERYYB'
#  index_name:     'documentation_theme_jekyll_designers'
port: 4009

exclude:
  - _site
  - _drafts
  - configs/
  - doc/mydoc_writers*

# same for all
host: 127.0.0.1
feedback_email: yang_yj19931231@163.com

# these settings should work, but they don't seem to apply the right highlighting

#highlighter: rouge
#markdown: kramdown
#kramdown:
#  input: GFM
#  auto_ids: true
#  hard_wrap: false
#  syntax_highlighter: rouge

highlighter: rouge
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "tables", "with_toc_data"]


collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

